# Introduction to PyTorch  

In [1]:
import torch

## Code examples

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.7726, 0.2833],
        [0.6680, 0.8823],
        [0.3692, 0.0787],
        [0.4823, 0.6398],
        [0.7384, 0.3646],
        [0.6558, 0.5927],
        [0.8253, 0.2452],
        [0.8744, 0.9169],
        [0.1971, 0.9367],
        [0.3534, 0.1316]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.4576, 0.3540],
         [0.1967, 0.9061]],

        [[0.8965, 0.8699],
         [0.8067, 0.1370]],

        [[0.8025, 0.8915],
         [0.6548, 0.1652]],

        [[0.7267, 0.0938],
         [0.7145, 0.4816]],

        [[0.0422, 0.8449],
         [0.8759, 0.2855]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [9]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.7768, 0.3727],
         [0.4909, 0.6570]],

        [[0.9544, 0.2960],
         [0.0708, 0.3888]],

        [[0.6493, 0.7254],
         [0.4242, 0.8061]]])


In [10]:
print(  A.dim()   )

3


In [11]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [12]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [13]:
B=torch.rand(3,5)
print(B)

tensor([[0.3622, 0.0469, 0.9166, 0.2912, 0.4488],
        [0.6072, 0.3522, 0.7803, 0.1210, 0.7523],
        [0.2143, 0.8659, 0.2424, 0.5141, 0.3843]])


In [14]:
print( B.dim()  )

2


In [15]:
print( B.size()  )

torch.Size([3, 5])


In [16]:
print( B.size(0) )

3


In [17]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [18]:
x=torch.rand(7)
print(x)

tensor([0.8064, 0.0922, 0.7600, 0.1740, 0.6124, 0.6438, 0.2687])


In [19]:
print( x.dim() )

1


In [20]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [21]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.0648, 0.1701],
        [0.5181, 0.4922]])

tensor([[0.1946, 0.4514],
        [0.6291, 0.6935]])

tensor([[0.3892, 0.9027],
        [1.2583, 1.3869]])

tensor([[0.3892, 0.9027],
        [1.2583, 1.3869]])

tensor([[0.0126, 0.0768],
        [0.3259, 0.3413]])


### Floats versus integers

In [22]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [23]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [24]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [25]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [26]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [27]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([9, 3, 1, 4, 0, 5, 6, 2, 7, 8])
torch.LongTensor


In [28]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [29]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [30]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [31]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [32]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [33]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [34]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [35]:
print( y[0] )

tensor([0, 1])


In [36]:
print( y[1] )

tensor([2, 3])


In [37]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [38]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [39]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [40]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [41]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [42]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [43]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [44]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [47]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [48]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>


## Exercises

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [53]:
# Write your code here
A = torch.Tensor([[1,2],[3,4]])
B = torch.Tensor([[10,20],[30,40]])
C = A+B

print(A)
print(B)
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [54]:
# Write your code here
print(A.dim())
print(A.size())
print(A.type())

2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [56]:
# Write your code here
A = A.long()
print(A.type())

torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [60]:
# Write your code here
D = torch.rand(5,2,3)
print(D)
print(D.type())
print(D.dim())
print(D.size())
print(D[0,:,0].size())

tensor([[[0.1188, 0.8583, 0.5364],
         [0.2773, 0.9197, 0.7988]],

        [[0.9489, 0.9308, 0.5226],
         [0.1077, 0.7751, 0.2285]],

        [[0.6085, 0.7273, 0.4251],
         [0.3427, 0.9480, 0.7332]],

        [[0.0585, 0.8533, 0.2829],
         [0.9336, 0.1653, 0.4742]],

        [[0.6239, 0.5677, 0.3762],
         [0.9680, 0.5884, 0.2780]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
torch.Size([2])


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [61]:
# Write your code here
E = torch.zeros(2,3,4,5)
print(E)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
